# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
    config.ssh.private_key_path = ["./ssh_user_key/id_ecdsa"]
    
    config.vm.synced_folder ".", "/vagrant", disabled: true
    
    config.vm.provider "docker" do |d|
      d.build_dir = "."
      d.dockerfile = "./Dockerfile"
      d.create_args = ["--privileged"]
      d.has_ssh = true
    end
  
    # Ubuntu Developer VM
    config.vm.define "dev1" do |dev1|
      dev1.vm.hostname = "dev1"
      dev1.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh", auto_correct: true
    end
end
