# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    
    config.vm.provider "tart" do |tart|
      tart.image = "ghcr.io/cirruslabs/ubuntu:latest"
      tart.name = "lorien"
      tart.disk = 20
      tart.cpus = 4
      tart.memory = 8192
    end

    config.ssh.username = "admin"
    config.ssh.password = "admin"

    config.vm.define "lorien" do |lorien|
      lorien.vm.hostname = "lorien"
      
      # Run Ansible provisioner once for all VMs at the end
      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../configure.yml"

        # On macOS with Apple Silicon, some playbooks are not supported.
        # In the configure.yml, these are tagged with
        # "not-supported-on-vagrant-arm64".
        # We have to skip them here.
        ansible.skip_tags = [ "not-supported-on-vagrant-arm64" ]
        
        # Debug by uncommenting the following line:
        #ansible.verbose = "vvv"
        
        # Vagrant fails to detect the Ansible version. Thus we force it to
        # use v2.
        ansible.compatibility_mode = "2.0"

        # We deliberately deviate from the Hetzner configuration using "root"
        # as the remote user. Tart only supports "admin" as the remote user.
        ansible.force_remote_user = true

        ansible.limit = "all"
        ansible.extra_vars = {

          ansible_user: "admin",
          remote_user: "admin",
          
          # When executing `vagrant provision` we run in non-interactive mode.
          # Thus, we need to hand over the passwords which would usually be
          # prompted.
          ansible_user_password: "gandalf",
          desktop_user_password: "galadriel",

          # Public key is copied from ../ssh_user_key/id_ecdsa.pub
          ssh_public_key: "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAGodZbJdnsMg04quzgawuI5wCQtxCTnLzevJbM8skRBc93exnvRrmYx9UWXlSVSP1MzYBADtcEqK36qYFx5jQRc3QEvKYO501QIJAKsixKvnPWkrPg19L6QHWHA9D0EBDNG2WZYAMySrZQHsnRpmIAEct0bV6V+7i7X/GjtxP4ctI0q6A== vagrant@testlab",
        }
        ansible.groups = {
          "dev" => ["lorien"],
          "dev:vars" => {
            "ansible_user" => "gandalf",
            "desktop_user" => "galadriel"
          }
        }
      end
    end
end
