# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    
    config.vm.provider "tart" do |tart|
      tart.image = "ghcr.io/cirruslabs/ubuntu:latest"
      tart.name = "lorien"
      tart.disk = 30
      tart.cpus = 4
      tart.memory = 8192
    end

    config.ssh.username = "admin"
    config.ssh.password = "admin"

    config.vm.define "lorien" do |lorien|
      lorien.vm.hostname = "lorien"
    end
end
