---
# AWS Configure Playbook
# Configures AWS EC2 instances using existing setup playbooks

- name: Configure AWS Development Environment
  import_playbook: configure.yml
  vars:
    # Use AWS-specific inventory
    ansible_inventory: inventories/aws/aws_ec2.yml
    # Target the aws_dev group created by dynamic inventory
    target_hosts: aws_dev
