---
- import_playbook: playbooks/setup-users.yml
- import_playbook: playbooks/setup-basics.yml
- import_playbook: playbooks/setup-homebrew.yml

# Setup desktop environment
#
# These playbooks are not supported on Vagrant with Docker provider
# I assume that the underlying reason is that the docker image is minimized
# and cannot be unminimized.
#
- import_playbook: playbooks/setup-desktop.yml
- import_playbook: playbooks/setup-keyring.yml
- import_playbook: playbooks/setup-desktop-apps.yml

# Restore backup
- import_playbook: ./restore.yml
