---
# AWS Configure Playbook
# Configures AWS EC2 instances using existing setup playbooks

- name: Configure AWS Development Environment
  import_playbook: configure.yml
  vars:
    # Target the linux group created by dynamic inventory
    target_hosts: linux
