---
- name: Destroy all cloud resources
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    providers:
      - hcloud
      - aws # Destroying AWS takes ages, that's why it's at the end
  
  tasks:
    - name: Destroy provider resources
      include_tasks: "destroy-{{ item }}-tasks.yml"
      loop: "{{ providers }}"
      ignore_errors: true  # Continue if one provider fails
      register: destroy_results

    - name: Display results
      debug:
        msg: "Provider {{ item.item }} destruction completed"
      loop: "{{ destroy_results.results }}"
      when: destroy_results.results is defined
