---
# AWS Destroy Playbook
# Completely destroys AWS EC2 development environment and all associated resources

- name: Destroy AWS EC2 Development Environment
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aws_region: "{{ aws_default_region | default('eu-north-1') }}"
    aws_security_group_name: "ansible-sg"
    aws_instance_states_to_terminate: ["running", "pending", "stopping", "stopped"]

  tasks:
    - name: Get all EC2 instances created by ansible
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          instance-state-name: "{{ aws_instance_states_to_terminate }}"
      register: ansible_instances

    - name: Display instances to be terminated
      ansible.builtin.debug:
        msg:
          - "Found {{ ansible_instances.instances | length }} instance(s) to terminate:"
          - "{{ ansible_instances.instances | map(attribute='instance_id') | list }}"
          - "Security Group: {{ aws_security_group_name }}"
      when: ansible_instances.instances | length > 0

    - name: Terminate all ansible-created EC2 instances
      amazon.aws.ec2_instance:
        instance_ids: "{{ ansible_instances.instances | map(attribute='instance_id') | list }}"
        region: "{{ aws_region }}"
        state: terminated
        wait: true
        wait_timeout: 300
      when: ansible_instances.instances | length > 0
      register: terminated_instances

    - name: Wait for instances to be fully terminated
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        instance_ids: "{{ ansible_instances.instances | map(attribute='instance_id') | list }}"
      register: instance_status
      until: instance_status.instances | selectattr('state.name', 'ne', 'terminated') | list | length == 0
      retries: 30
      delay: 10
      when: ansible_instances.instances | length > 0

    - name: Delete security group
      amazon.aws.ec2_security_group:
        name: "{{ aws_security_group_name }}"
        region: "{{ aws_region }}"
        state: absent
      register: sg_deletion
      until: sg_deletion is succeeded
      retries: 30
      delay: 10

    - name: Verify all resources are cleaned up
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          "tag:CreatedBy": "ansible"
          instance-state-name: "{{ aws_instance_states_to_terminate }}"
      register: remaining_instances

    - name: Remove host keys from known_hosts
      ansible.builtin.known_hosts:
        name: "{{ item.public_ip_address }}"
        state: absent
      when: 
        - ansible_instances.instances | length > 0
        - item.public_ip_address is defined
      loop: "{{ ansible_instances.instances }}"

    - name: Display cleanup results
      ansible.builtin.debug:
        msg:
          - "AWS Environment Cleanup Complete!"
          - ""
          - "- Terminated: {{ terminated_instances.instance_ids | default([]) | length }}"
          - "- Remaining: {{ remaining_instances.instances | length }}"
          - "- Security group deleted: {{ 'Yes' if sg_deletion is not failed else 'Failed - may need manual cleanup' }}"

    - name: Warn about remaining resources
      ansible.builtin.fail:
        msg:
          - "WARNING: {{ remaining_instances.instances | length }} instances still exist!"
          - "Instance IDs: {{ remaining_instances.instances | map(attribute='instance_id') | list }}"
          - "Please check AWS console and terminate manually if needed."
      when: remaining_instances.instances | length > 0
