---
- name: Restore home folder files
  hosts: linux
  become: true

  vars:
    ansible_user: "{{ my_ansible_user }}"
    restore_user: "{{ desktop_users[0].name }}"

  tasks:

    - name: Restore home folder files
      include_tasks: restore.yml
      vars:
        users: "{{ [restore_user] }}"
        backup_file: "home-folder-files-backup.tar.gz"
        destination_beneath_home: ""

    - name: Set permissions for secrets correctly
      file:
        path: "/home/{{ restore_user }}/.envrc"
        owner: "{{ restore_user }}"
        group: "{{ restore_user }}"
        mode: '0600'
