#SPDX-License-Identifier: MIT-0
---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: true

- name: Clone ai-agent-workspace source repository
  ansible.builtin.git:
    repo: https://github.com/wonderbird/ai-agent-workspace
    dest: /home/{{ item }}/Documents/Cline/ai-agent-workspace
    version: main
    update: yes
    force: no
  become: true
  become_user: "{{ item }}"
  loop: "{{ login_user_names }}"
