#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: Stefan Boos
  namespace: wonderbird
  role_name: nerd_font
  description: Install the Hack Nerd Font for desktop users (fc-cache rebuilt per user)
  company: n.a.
  issue_tracker_url: http://github.com/wonderbird/ansible-all-my-things/issues
  license: MIT
  min_ansible_version: 2.19
  galaxy_tags: []

dependencies: []
