---
- name: Setup developer server
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - ../playbooks/vars-secrets.yml
    - ../inventories/group_vars/all/vars.yml
    - ../inventories/group_vars/linux/vars.yml
    - ../inventories/group_vars/hcloud/vars.yml
    - ../inventories/group_vars/hcloud_linux/vars.yml

  vars:
    # Check `hcloud image list | grep ubuntu` for a list of available images.
    image: "ubuntu-24.04"
    hcloud_server_type: "{{ hcloud_default_type | default('hcloud_default_type must be specified') }}"
    hcloud_server_location: "{{ hcloud_default_location | default('hcloud_default_location must be specified') }}"
    hcloud_ssh_key_name: "{{ my_ssh_key_name | default('my_ssh_key_name must be configured in vars-secrets.yml') }}"
    hcloud_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"

  tasks:
    - name: Ensure required variables are defined
      assert:
        that:
          - hcloud_token is defined
          - hcloud_token | length > 0
        fail_msg: "The environment variable HCLOUD_TOKEN must be defined"

    - name: Create developer server
      hetzner.hcloud.server:
        state: present
        name: hobbiton
        labels:
          platform: "linux"
        server_type: "{{ hcloud_server_type }}"
        image: "{{ image }}"
        location: "{{ hcloud_server_location }}"
        ssh_keys: "{{ hcloud_ssh_key_name }}"
      register: hcloud

    - name: Refresh inventory to ensure new host is available
      meta: refresh_inventory

- hosts: hcloud
  remote_user: root
  gather_facts: False

  vars:
    ansible_user: "root"

  tasks:
    - name: Wait for host to become reachable
      wait_for_connection:
