---
- name: Setup developer server
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - ../inventories/group_vars/linux/vars.yml
    - ../inventories/group_vars/hcloud/vars.yml
    - ../inventories/group_vars/hcloud_linux/vars.yml

  vars:
    # Check `hcloud image list | grep ubuntu` for a list of available images.
    image: "ubuntu-24.04"
    hcloud_server_type: "{{ hcloud_default_type | default('hcloud_default_type must be specified') }}"
    hcloud_server_location: "{{ hcloud_default_location | default('hcloud_default_location must be specified') }}"
    hcloud_ssh_key_name: "{{ my_ssh_key_name | default('my_ssh_key_name must be configured in inventory/group_vars/all/vault.yml') }}"
    hcloud_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"

  tasks:
    - name: Ensure required variables are defined
      assert:
        that:
          - hcloud_token is defined
          - hcloud_token | length > 0
        fail_msg: "The environment variable HCLOUD_TOKEN must be defined"

    - name: Create developer server
      hetzner.hcloud.server:
        state: present
        name: hobbiton
        labels:
          platform: "linux"
        server_type: "{{ hcloud_server_type }}"
        image: "{{ image }}"
        location: "{{ hcloud_server_location }}"
        ssh_keys: "{{ hcloud_ssh_key_name }}"
      register: hcloud

    - name: Refresh inventory to ensure new host is available
      meta: refresh_inventory

- hosts: hcloud
  remote_user: root
  gather_facts: False

  vars:
    ansible_user: "root"

  tasks:

    #####
    # Accept SSH host key of fresh server
    #
    # This implements Daniel Davis's suggestion from https://gist.github.com/shirou/6928012?permalink_comment_id=4059919#gistcomment-4059919
    #
    # Important additions:
    # 
    # - ssh-keyscan prints comments to stdout instead of stderr.
    #   The -q option must be used to suppress these comments.
    #   Otherwise the known_hosts module will fail when processing the comments.
    #
    # - Retries and delay are used to wait for the server to become available.
    #   Usually the server is available on the 3rd try.
    #
    # I was directed to the correct path by the stack overflow answer by nikobelia: https://stackoverflow.com/a/32338480
    - name: Scan for SSH host keys
      local_action:
        module: shell
        cmd: ssh-keyscan -q {{ ansible_host }}
      changed_when: False
      retries: 6
      delay: 10
      register: ssh_scan

    - name: Update known_hosts
      local_action:
        module: known_hosts
        key: "{{ item }}"
        name: "{{ ansible_host }}"
      with_items: "{{ ssh_scan.stdout_lines }}"
    #####
