#SPDX-License-Identifier: MIT-0
---
- name: Install Chocolatey packages
  win_chocolatey:
    name:
      - claude
      - nvm

- name: Install Nodejs LTS
  win_shell: nvm install lts
  args:
    creates: C:\ProgramData\nvm\v22.18.0\node.exe

- name: Activate Nodejs LTS
  win_shell: nvm use lts
