---
# AWS Windows-specific overrides
# These override both platform and provider defaults for AWS Windows instances

# AWS Windows instances use 'Administrator' as admin user
admin_user_on_fresh_system: "Administrator"

# Windows-specific shell configuration
ansible_shell_type: powershell
ansible_shell_executable: powershell