#!/usr/bin/env python3
"""unittest suite for check-version-update-order.py.

Run directly: python3 scripts/version-update-order/test_check_version_update_order.py

Fixtures are generated by mutating the live
playbooks/update-versions/*.yml pair into a temporary directory rather than
by checking in copies of a 600-line playbook, so a fixture cannot drift away
from the file the gate actually protects (Principle XI).
"""
import importlib.util
import io
import contextlib
import shutil
import re
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
PLAYBOOK_DIR = REPO / "playbooks" / "update-versions"
PHASE_MARKER = "    # --- Apply updates to role defaults files ---"

_spec = importlib.util.spec_from_file_location(
    "check_version_update_order",
    Path(__file__).parent / "check-version-update-order.py",
)
check_version_update_order = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(check_version_update_order)


def split_blocks(text):
    """Split a playbook body into blank-line-separated blocks."""
    return text.split("\n\n")


def join_blocks(blocks):
    return "\n\n".join(blocks)


def _dedent(snippet):
    """Split a snippet into (relative indent, content) pairs."""
    lines = snippet.strip("\n").split("\n")
    base = min(len(l) - len(l.lstrip()) for l in lines if l.strip())
    return [(len(l) - len(l.lstrip()) - base, l.strip()) if l.strip() else (0, "")
            for l in lines]


def swap(text, old, new, count=1):
    """Replace `old` with `new` wherever it sits, at whatever indentation.

    The fixtures must not hardcode the playbook's indentation: the tools are
    wrapped in block/rescue, so every task sits deeper than it used to and a
    literal replace would silently match nothing.
    """
    old_lines, new_lines = _dedent(old), _dedent(new)
    pattern = r"(?P<indent>[ \t]*)" + re.escape(old_lines[0][1]) + "\n"
    for rel, content in old_lines[1:]:
        pattern += (r"(?P=indent)" + " " * rel + re.escape(content) + "\n"
                    if content else "\n")
    match = re.search(pattern, text)
    if match is None:
        raise AssertionError(f"snippet not found at any indentation: {old_lines[0][1]!r}")
    indent = match.group("indent")
    replacement = "".join((indent + " " * rel + content + "\n") if content else "\n"
                          for rel, content in new_lines)
    return text[:match.start()] + replacement + text[match.end():], match.group(0)


def block_index(blocks, needle):
    for i, block in enumerate(blocks):
        if needle in block:
            return i
    raise AssertionError(f"no block containing {needle!r}")


class CheckerFixture:
    """A temporary copy of the update-versions playbook pair."""

    def __init__(self, tmpdir):
        self.dir = Path(tmpdir)
        for name in ("perform-updates.yml", "query-versions.yml"):
            shutil.copy(PLAYBOOK_DIR / name, self.dir / name)

    @property
    def target(self):
        return self.dir / "perform-updates.yml"

    def read(self):
        return self.target.read_text()

    def write(self, text):
        self.target.write_text(text)

    def run(self):
        """Run the checker and return (exit_code, stdout)."""
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            code = check_version_update_order.main([str(self.target)])
        return code, out.getvalue()


class CheckVersionUpdateOrderTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.fixture = CheckerFixture(self._tmp.name)

    def test_correct_reorder_passes(self):
        code, out = self.fixture.run()
        self.assertIn("0 ordering violation(s), "
                      "0 unattributable fetch(es), 0 pairing violation(s)", out)
        self.assertIn("analysed 18/18 roles", out)
        self.assertEqual(code, 0)

    def test_transposed_stat_registers_break_pairing(self):
        """Swapping dolt's two stat registers is caught by platform pairing.

        Every positional check passes on this edit: both writes still follow
        both fetches, and both aliases are still adjacent to their includes.
        """
        text = self.fixture.read()
        text, _ = swap(
            text,
            '- pin: dolt_sha256_amd64\n  value: "{{ _dolt_amd64_stat.stat.checksum }}"',
            '- pin: dolt_sha256_amd64\n  value: "{{ _PLACEHOLDER_stat.stat.checksum }}"')
        text, _ = swap(
            text,
            '- pin: dolt_sha256_arm64\n  value: "{{ _dolt_arm64_stat.stat.checksum }}"',
            '- pin: dolt_sha256_arm64\n  value: "{{ _dolt_amd64_stat.stat.checksum }}"')
        text = text.replace("_PLACEHOLDER_stat", "_dolt_arm64_stat")
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("2 pairing violation(s)", out)
        self.assertIn("'dolt_sha256_amd64' (amd64) is written from "
                      "'_dolt_arm64_stat.stat.checksum' (arm64)", out)
        self.assertIn("transposed platform values", out)
        self.assertEqual(code, 1)

    def test_transposed_checksum_sources_break_pairing(self):
        """Swapping rtk's two checksum sources is caught too.

        Distinctness of the written digests cannot detect this: two valid but
        swapped digests are written and no task fails.
        """
        text = self.fixture.read()
        text, _ = swap(
            text,
            '- pin: rtk_sha256_x86_64_musl\n  value: "{{ fetched_rtk_sha256_x86_64_musl }}"',
            '- pin: rtk_sha256_x86_64_musl\n  value: "{{ _PLACEHOLDER }}"')
        text, _ = swap(
            text,
            '- pin: rtk_sha256_aarch64_gnu\n  value: "{{ fetched_rtk_sha256_aarch64_gnu }}"',
            '- pin: rtk_sha256_aarch64_gnu\n  value: "{{ fetched_rtk_sha256_x86_64_musl }}"')
        text = text.replace("_PLACEHOLDER", "fetched_rtk_sha256_aarch64_gnu")
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("2 pairing violation(s)", out)
        self.assertIn("transposed platform values", out)
        self.assertEqual(code, 1)

    def test_cross_tool_checksum_source_breaks_pairing(self):
        """A digest taken from another tool's checksum fact is caught.

        Platform tokens agree (amd64 to amd64) and bd's fetches still precede
        bd's first write, so ordering and platform pairing both pass. Only the
        source-name rule sees it.
        """
        text, _ = swap(
            self.fixture.read(),
            '- pin: beads_viewer_sha256_amd64\n  value: "{{ fetched_beads_viewer_sha256_amd64 }}"',
            '- pin: beads_viewer_sha256_amd64\n  value: "{{ fetched_beads_go_sha256_amd64 }}"')
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("1 pairing violation(s)", out)
        self.assertIn("'beads_viewer_sha256_amd64' is written from "
                      "'fetched_beads_go_sha256_amd64'", out)
        self.assertIn("another tool's checksum", out)
        self.assertEqual(code, 1)

    def test_relocated_phase_marker_narrows_scope(self):
        """Moving the apply-phase marker must not yield a clean subset."""
        text = self.fixture.read()
        self.assertIn(PHASE_MARKER, text)
        text = text.replace(PHASE_MARKER + "\n\n", "", 1)
        text = text.replace("    # GitHub CLI\n",
                            PHASE_MARKER + "\n\n    # GitHub CLI\n", 1)
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("SCOPE ERROR", out)
        self.assertIn("the apply-phase marker moved or a tool was dropped", out)
        self.assertIn("violations below are NOT trustworthy", out)
        self.assertEqual(code, 1)

    def test_unattributable_fetch_fails_closed(self):
        """A fetch the checker cannot attribute to a role is an error."""
        text = self.fixture.read().rstrip("\n")
        text += "\n\n" + "\n".join([
            "    - name: Fetch mystery tool metadata",
            "      ansible.builtin.uri:",
            '        url: "https://example.invalid/metadata.json"',
            "      register: _mystery_metadata",
        ]) + "\n"
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("1 unattributable fetch(es)", out)
        self.assertIn("cannot attribute apply-phase fetch to a role", out)
        self.assertIn("Fetch mystery tool metadata", out)
        self.assertEqual(code, 1)

    def test_added_tool_must_be_registered_in_query_versions(self):
        """A correctly-added tool #19 is reported as a registration gap.

        The tool is wired here in the right order -- fetch before write -- so
        no ordering or pairing check fires. What is missing is the
        stale-check clause in query-versions.yml, and the message must say so.
        """
        text = self.fixture.read().rstrip("\n")
        text += "\n\n" + "\n".join([
            "    # newtool",
            "    - name: Download newtool binary for sha256 computation",
            "      ansible.builtin.get_url:",
            '        url: "https://example.invalid/{{ fetched_newtool_tag }}/newtool"',
            '        dest: "/tmp/newtool-{{ fetched_newtool_tag }}"',
            "        mode: '0644'",
            "",
            "    - name: Update newtool_version in newtool role defaults",
            "      ansible.builtin.replace:",
            '        path: "{{ _roles_dir }}/newtool/defaults/main.yml"',
            "        regexp: 'newtool_version:\\s*\"[^\"]+\"'",
            "        replace: 'newtool_version: \"{{ fetched_newtool_tag }}\"'",
        ]) + "\n"
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("SCOPE ERROR", out)
        self.assertIn("analysed 19 roles, expected 18", out)
        self.assertIn("a tool was added here but not to query-versions.yml's "
                      "stale check", out)
        self.assertIn("Constitution II", out)
        self.assertIn("0 ordering violation(s), "
                      "0 unattributable fetch(es), 0 pairing violation(s), "
                      "1 bypass violation(s)", out)
        self.assertEqual(code, 1)

    def append_task(self, lines):
        text = self.fixture.read().rstrip("\n")
        self.fixture.write(text + "\n\n" + "\n".join(lines) + "\n")

    def test_raw_replace_beside_existing_include_is_bypass(self):
        """A raw replace for a tool that already has an include is caught.

        The role is already counted, so SCOPE stays 18 == 18. Only BYPASS sees
        a write that skips the exactly-once check of write-pins.yml.
        """
        self.append_task([
            "    - name: Update direnv_version in direnv role defaults",
            "      ansible.builtin.replace:",
            '        path: "{{ _roles_dir }}/direnv/defaults/main.yml"',
            "        regexp: 'direnv_version:\\s*\"[^\"]+\"'",
            "        replace: 'direnv_version: \"{{ fetched_direnv_tag }}\"'",
        ])

        code, out = self.fixture.run()
        self.assertIn("1 bypass violation(s)", out)
        self.assertIn("file edited without tasks/write-pins.yml", out)
        self.assertIn("Update direnv_version in direnv role defaults", out)
        self.assertNotIn("SCOPE ERROR", out)
        self.assertEqual(code, 1)

    def test_short_name_lineinfile_off_rolepath_is_bypass(self):
        """A short module name with another path spelling is caught too."""
        self.append_task([
            "    - name: Rewrite direnv_version line",
            "      lineinfile:",
            '        path: "{{ playbook_dir }}/../../roles/direnv/defaults/main.yml"',
            "        regexp: '^direnv_version:(.*)$'",
            "        line: 'direnv_version: \"v0.0.0\"'",
            "        backrefs: true",
        ])

        code, out = self.fixture.run()
        self.assertIn("1 bypass violation(s)", out)
        self.assertIn("Rewrite direnv_version line", out)
        self.assertEqual(code, 1)

    def test_comment_mentioning_copy_is_not_bypass(self):
        """A comment or a var named like a module is not a file edit."""
        text = self.fixture.read()
        anchor = "    - name: Write direnv pins\n"
        self.assertIn(anchor, text)
        text = text.replace(anchor, anchor + "      # copy: not a task\n"
                            "      # url_template: not a module\n", 1)
        text = text.replace(
            '        pin_file: "{{ _roles_dir }}/direnv/defaults/main.yml"\n',
            '        pin_file: "{{ _roles_dir }}/direnv/defaults/main.yml"\n'
            '        url_template: "unused"\n', 1)
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("0 bypass violation(s)", out)
        self.assertEqual(code, 0)

    def test_release_include_without_asset_declaration_is_asset_violation(self):
        """Dropping a tool's asset patterns is caught, not silently accepted.

        Without a declaration the include accepts whatever the API calls the
        latest release, including one that carries no asset this tool installs.
        """
        text = self.fixture.read()
        text, _ = swap(
            text,
            "required_asset_regexes:\n  - '^Hack\\.zip$'",
            "required_asset_regexes: []")
        self.fixture.write(re.sub(r"[ \t]*required_asset_regexes: \[\]\n", "", text, count=1))

        code, out = self.fixture.run()
        self.assertIn("1 asset violation(s)", out)
        self.assertIn("Fetch Nerd Fonts (Hack) upstream version", out)
        self.assertIn("declares neither required_asset_regexes nor "
                      "release_carries_no_consumed_asset", out)
        self.assertEqual(code, 1)

    def test_release_include_with_stated_reason_is_accepted(self):
        """A tool installed outside the release assets states that instead."""
        text = self.fixture.read()
        text, _ = swap(
            text,
            "required_asset_regexes:\n  - '^Hack\\.zip$'",
            'release_carries_no_consumed_asset: "installed from a distribution '
            'package, not from release assets"')
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("0 asset violation(s)", out)
        self.assertEqual(code, 0)

    def test_ordering_violation_inside_a_block_is_still_caught(self):
        """Nesting the tools in block/rescue must not hide an ordering error.

        Every task now sits deeper than it used to, so a checker that keyed on
        indentation would silently stop reporting a fetch after a write.
        """
        text = self.fixture.read()
        text, _ = swap(
            text,
            '- name: Record that dolt_sql_server was updated',
            '- name: "upstream: Download dolt again after the write"\n'
            '  ansible.builtin.get_url:\n'
            '    url: "https://example.invalid/{{ fetched_dolt_tag }}/late.tar.gz"\n'
            '    dest: "/tmp/dolt-late.tar.gz"\n'
            "    mode: '0644'\n"
            '\n'
            '- name: Record that dolt_sql_server was updated')
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("1 ordering violation(s)", out)
        self.assertIn("fetch for 'dolt_sql_server' runs after its first write", out)
        self.assertEqual(code, 1)

    def test_rescue_tasks_are_not_unattributable_fetches(self):
        """A rescue's include of the failure recorder is not a fetch."""
        code, out = self.fixture.run()
        self.assertIn("0 unattributable fetch(es)", out)
        self.assertIn("Record the apply failure of", self.fixture.read())
        self.assertEqual(code, 0)

    def test_phase_marker_keeps_its_indentation(self):
        """The apply-phase marker must stay where the checker slices on it."""
        self.assertIn(PHASE_MARKER + "\n", self.fixture.read())

    def test_renamed_tracked_tool_is_caught_although_the_count_holds(self):
        """A typo in _tracked_tools drops a tool out of the run accounting.

        The count stays 18, so only comparing the sets catches it.
        """
        text = self.fixture.read()
        text, _ = swap(text, "- beads_viewer\n- beads_rust",
                       "- beads_viewerr\n- beads_rust")
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("analysed 18/18 roles", out)
        self.assertIn("_tracked_tools does not match the roles written here", out)
        self.assertIn("beads_viewer", out)
        self.assertEqual(code, 1)

    def test_reordered_value_before_pin_is_pairing_parse_error(self):
        """A pin whose value line is not directly after it cannot be skipped."""
        text = self.fixture.read()
        text, _ = swap(
            text,
            '- pin: dolt_sha256_arm64\n  value: "{{ _dolt_arm64_stat.stat.checksum }}"',
            '- value: "{{ _dolt_arm64_stat.stat.checksum }}"\n  pin: dolt_sha256_arm64')
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("PAIRING parse:", out)
        self.assertIn("Write dolt_sql_server pins", out)
        self.assertEqual(code, 1)


if __name__ == "__main__":
    unittest.main(verbosity=2)
