#!/usr/bin/env python3
"""unittest suite for check-apply-order.py.

Run directly: python3 scripts/test_check_apply_order.py

Fixtures are generated by mutating the live
playbooks/update-versions/*.yml pair into a temporary directory rather than
by checking in copies of a 600-line playbook, so a fixture cannot drift away
from the file the gate actually protects (Principle XI).
"""
import importlib.util
import io
import contextlib
import shutil
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PLAYBOOK_DIR = REPO / "playbooks" / "update-versions"
PHASE_MARKER = "    # --- Apply updates to role defaults files ---"

_spec = importlib.util.spec_from_file_location(
    "check_apply_order", Path(__file__).parent / "check-apply-order.py"
)
check_apply_order = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(check_apply_order)


def split_blocks(text):
    """Split a playbook body into blank-line-separated blocks."""
    return text.split("\n\n")


def join_blocks(blocks):
    return "\n\n".join(blocks)


def block_index(blocks, needle):
    for i, block in enumerate(blocks):
        if needle in block:
            return i
    raise AssertionError(f"no block containing {needle!r}")


class CheckerFixture:
    """A temporary copy of the update-versions playbook pair."""

    def __init__(self, tmpdir):
        self.dir = Path(tmpdir)
        for name in ("perform-updates.yml", "query-versions.yml"):
            shutil.copy(PLAYBOOK_DIR / name, self.dir / name)

    @property
    def target(self):
        return self.dir / "perform-updates.yml"

    def read(self):
        return self.target.read_text()

    def write(self, text):
        self.target.write_text(text)

    def run(self):
        """Run the checker and return (exit_code, stdout)."""
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            code = check_apply_order.main([str(self.target)])
        return code, out.getvalue()


class CheckApplyOrderTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.fixture = CheckerFixture(self._tmp.name)

    def test_correct_reorder_passes(self):
        code, out = self.fixture.run()
        self.assertIn("0 ordering violation(s), 0 adjacency violation(s), "
                      "0 unattributable fetch(es), 0 pairing violation(s)", out)
        self.assertIn("analysed 18/18 roles", out)
        self.assertEqual(code, 0)

    def test_batched_includes_break_adjacency(self):
        """Hoisting both rtk includes ahead of their Save aliases is caught.

        This edit satisfies the per-tool ordering check while leaving both
        aliases reading the last include's value -- the silent corruption the
        adjacency check exists to detect.
        """
        blocks = split_blocks(self.fixture.read())
        names = [
            "Fetch rtk x86_64-musl checksum",
            "Save rtk x86_64-musl fetched checksum",
            "Fetch rtk aarch64-gnu checksum",
            "Save rtk aarch64-gnu fetched checksum",
        ]
        slots = [block_index(blocks, n) for n in names]
        batched = [blocks[slots[0]], blocks[slots[2]], blocks[slots[1]], blocks[slots[3]]]
        for slot, block in zip(slots, batched):
            blocks[slot] = block
        self.fixture.write(join_blocks(blocks))

        code, out = self.fixture.run()
        self.assertIn("1 adjacency violation(s)", out)
        self.assertIn("Save rtk aarch64-gnu fetched checksum", out)
        self.assertIn("does not immediately follow its include", out)
        self.assertEqual(code, 1)

    def test_transposed_stat_registers_break_pairing(self):
        """Swapping dolt's two stat registers is caught by platform pairing.

        Every positional check passes on this edit: both writes still follow
        both fetches, and both aliases are still adjacent to their includes.
        """
        text = self.fixture.read()
        text = text.replace(
            'replace: \'dolt_sha256_amd64: "{{ _dolt_amd64_stat.stat.checksum }}"\'',
            'replace: \'dolt_sha256_amd64: "{{ _PLACEHOLDER_stat.stat.checksum }}"\'',
        ).replace(
            'replace: \'dolt_sha256_arm64: "{{ _dolt_arm64_stat.stat.checksum }}"\'',
            'replace: \'dolt_sha256_arm64: "{{ _dolt_amd64_stat.stat.checksum }}"\'',
        ).replace("_PLACEHOLDER_stat", "_dolt_arm64_stat")
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("2 pairing violation(s)", out)
        self.assertIn("'dolt_sha256_amd64' (amd64) is written from "
                      "'_dolt_arm64_stat.stat.checksum' (arm64)", out)
        self.assertIn("transposed platform values", out)
        self.assertEqual(code, 1)

    def test_transposed_checksum_aliases_break_pairing(self):
        """Swapping rtk's two fetched_checksum aliases is caught too.

        This is the transposition form of the shared-fact hazard, which the
        distinctness of the written digests cannot detect: ten distinct but
        swapped digests are written and no task fails.
        """
        text = self.fixture.read()
        text = text.replace(
            'replace: \'rtk_sha256_x86_64_musl: "{{ fetched_rtk_sha256_x86_64_musl }}"\'',
            'replace: \'rtk_sha256_x86_64_musl: "{{ fetched_rtk_sha256_aarch64_gnu }}"\'',
        ).replace(
            'replace: \'rtk_sha256_aarch64_gnu: "{{ fetched_rtk_sha256_aarch64_gnu }}"\'',
            'replace: \'rtk_sha256_aarch64_gnu: "{{ fetched_rtk_sha256_x86_64_musl }}"\'',
        )
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("2 pairing violation(s)", out)
        self.assertIn("transposed platform values", out)
        self.assertEqual(code, 1)

    def test_replace_reading_raw_shared_fact_breaks_adjacency(self):
        """Deleting an alias and reading fetched_checksum directly is caught.

        This is the shape a plausible "simplify away the alias" cleanup takes.
        At that point in the play fetched_checksum holds the LAST include's
        value, so the write silently takes another architecture's digest.
        """
        text = self.fixture.read()
        text = text.replace(
            """    - name: Save Node.js x64 fetched checksum
      ansible.builtin.set_fact:
        fetched_node_sha256_x64: "{{ fetched_checksum }}"

""",
            "",
        ).replace(
            'replace: \'node_sha256_x64: "{{ fetched_node_sha256_x64 }}"\'',
            'replace: \'node_sha256_x64: "{{ fetched_checksum }}"\'',
        )
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("1 adjacency violation(s)", out)
        self.assertIn("Update node_sha256_x64 in nodejs role defaults", out)
        self.assertIn("does not immediately follow its include", out)
        self.assertEqual(code, 1)

    def test_cross_tool_checksum_source_breaks_pairing(self):
        """A digest taken from another tool's alias is caught.

        Platform tokens agree (amd64 to amd64) and bd's fetches still precede
        bd's first write, so ordering, adjacency and platform pairing all pass.
        Only the alias-name rule sees it.
        """
        text = self.fixture.read().replace(
            'replace: \'beads_viewer_sha256_amd64: "{{ fetched_beads_viewer_sha256_amd64 }}"\'',
            'replace: \'beads_viewer_sha256_amd64: "{{ fetched_beads_go_sha256_amd64 }}"\'',
        )
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("1 pairing violation(s)", out)
        self.assertIn("'beads_viewer_sha256_amd64' is written from "
                      "'fetched_beads_go_sha256_amd64'", out)
        self.assertIn("another tool's checksum", out)
        self.assertEqual(code, 1)

    def test_relocated_phase_marker_narrows_scope(self):
        """Moving the apply-phase marker must not yield a clean subset."""
        text = self.fixture.read()
        self.assertIn(PHASE_MARKER, text)
        text = text.replace(PHASE_MARKER + "\n\n", "", 1)
        text = text.replace("    # GitHub CLI\n",
                            PHASE_MARKER + "\n\n    # GitHub CLI\n", 1)
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("SCOPE ERROR", out)
        self.assertIn("the apply-phase marker moved or a tool was dropped", out)
        self.assertIn("violations below are NOT trustworthy", out)
        self.assertEqual(code, 1)

    def test_unattributable_fetch_fails_closed(self):
        """A fetch the checker cannot attribute to a role is an error."""
        text = self.fixture.read().rstrip("\n")
        text += "\n\n" + "\n".join([
            "    - name: Fetch mystery tool metadata",
            "      ansible.builtin.uri:",
            '        url: "https://example.invalid/metadata.json"',
            "      register: _mystery_metadata",
        ]) + "\n"
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("1 unattributable fetch(es)", out)
        self.assertIn("cannot attribute apply-phase fetch to a role", out)
        self.assertIn("Fetch mystery tool metadata", out)
        self.assertEqual(code, 1)

    def test_added_tool_must_be_registered_in_query_versions(self):
        """A correctly-added tool #19 is reported as a registration gap.

        The tool is wired here in the right order -- fetch before write -- so
        no ordering, adjacency or pairing check fires. What is missing is the
        stale-check clause in query-versions.yml, and the message must say so.
        """
        text = self.fixture.read().rstrip("\n")
        text += "\n\n" + "\n".join([
            "    # newtool",
            "    - name: Download newtool binary for sha256 computation",
            "      ansible.builtin.get_url:",
            '        url: "https://example.invalid/{{ fetched_newtool_tag }}/newtool"',
            '        dest: "/tmp/newtool-{{ fetched_newtool_tag }}"',
            "        mode: '0644'",
            "",
            "    - name: Update newtool_version in newtool role defaults",
            "      ansible.builtin.replace:",
            '        path: "{{ _roles_dir }}/newtool/defaults/main.yml"',
            "        regexp: 'newtool_version:\\s*\"[^\"]+\"'",
            "        replace: 'newtool_version: \"{{ fetched_newtool_tag }}\"'",
        ]) + "\n"
        self.fixture.write(text)

        code, out = self.fixture.run()
        self.assertIn("SCOPE ERROR", out)
        self.assertIn("analysed 19 roles, expected 18", out)
        self.assertIn("a tool was added here but not to query-versions.yml's "
                      "stale check", out)
        self.assertIn("Constitution II", out)
        self.assertIn("0 ordering violation(s), 0 adjacency violation(s), "
                      "0 unattributable fetch(es), 0 pairing violation(s)", out)
        self.assertEqual(code, 1)


if __name__ == "__main__":
    unittest.main(verbosity=2)
