# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
    config.ssh.private_key_path = ["../ssh_user_key/id_ecdsa"]

    # Allow using keys loaded into the SSH agent
    # This allows using the personal key for logging in as the user
    # my_ansible_user configured in the group_vars/all/vars.yml file.
    # A similar configuration is used for Hetzner Cloud and AWS VMs.
    config.ssh.keys_only = false
    
    config.vm.synced_folder ".", "/vagrant", disabled: true
    
    config.vm.provider "docker" do |d|
      d.build_dir = ".."
      d.dockerfile = "./docker/Dockerfile"
      d.create_args = ["--privileged"]
      d.has_ssh = true
    end
  
    # Ubuntu Developer VM
    config.vm.define "dagorlad" do |dagorlad|
      dagorlad.vm.hostname = "dagorlad"
      dagorlad.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh", auto_correct: true
    end
end
