# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
    config.ssh.private_key_path = ["../ssh_user_key/id_ecdsa"]

    # Allow using keys loaded into the SSH agent
    # This allows using the personal key for logging in as the user "gandalf".
    # A similar configuration is used for Hetzner Cloud and AWS VMs.
    config.ssh.keys_only = false
    
    config.vm.synced_folder ".", "/vagrant", disabled: true
    
    config.vm.provider "docker" do |d|
      d.build_dir = ".."
      d.dockerfile = "./docker/Dockerfile"
      d.create_args = ["--privileged"]
      d.has_ssh = true
    end
  
    # Ubuntu Developer VM
    config.vm.define "dagorlad" do |dagorlad|
      dagorlad.vm.hostname = "dagorlad"
      dagorlad.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh", auto_correct: true

      # Run Ansible provisioner once for all VMs at the end
      dagorlad.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../configure-linux.yml"
        ansible.vault_password_file = "../../ansible-vault-password.txt"

        # On macOS with Apple Silicon, some playbooks are not supported.
        # In the configure.yml, these are tagged with "not-supported-on-vagrant-arm64".
        # We have to skip them here.
        ansible.skip_tags = [
          "not-supported-on-vagrant-arm64",
          "not-supported-on-vagrant-docker"
        ]
        
        # Debug by uncommenting the following line:
        ansible.verbose = "vvv"
        
        # Vagrant fails to detect the Ansible version. Thus we force it to
        # use v2.
        ansible.compatibility_mode = "2.0"

        # Especially the setup-users.yml playbook uses "root" as the remote
        # user, because the Hetzner VMs have only root in the first place.
        # Thus, we must allow root here in order to mimic the target
        # environment.
        ansible.force_remote_user = false

        ansible.limit = "all"

        ansible.groups = {
          "linux" => ["dagorlad"],
          "linux:vars" => {
            "admin_user_on_fresh_system" => "vagrant",
          }
        }
      end
    end
end
