---
- hosts: dev
  tags: not-supported-on-vagrant-docker
  become: true

  vars_files:
    - vars-usernames.yml

  vars:
    ansible_user: "{{ my_ansible_user }}"

  tasks:
    - import_tasks: tasks/backup-directory.yml
      vars:
        path: "/home/{{ my_desktop_user }}/.local/share/keyrings"
        temp_backup_path: "/home/{{ my_desktop_user }}/keyrings-backup.tar.gz"
        dest: "{{ playbook_dir }}/../configuration/home/my_desktop_user/keyrings-backup.tar.gz"
