---
- hosts: dev
  tags: not-supported-on-vagrant-docker
  become: true

  vars_files:
    - vars-usernames.yml

  vars:
    ansible_user: "{{ my_ansible_user }}"
    config_remote_dir: "/home/{{ my_desktop_user }}/snap/chromium/common/chromium/Default"
    backup_remote_path: "/home/{{ my_desktop_user }}/chromium-backup.tar.gz"
    backup_local_path: "{{ playbook_dir }}/../configuration/home/my_desktop_user/chromium-backup.tar.gz"

  tasks:

    # TODO: smell - complicated error handling - consider using `block`, `rescue`, `always` - see p. 121 (147 in PDF) of Ansible for DevOps

    - name: Check if config directory exists
      stat:
        path: "{{ config_remote_dir }}"
      register: config_dir

    - name: Create tar.gz archive of config directory
      archive:
        path: "{{ config_remote_dir }}"
        dest: "{{ backup_remote_path }}"
        format: gz
        exclusion_patterns:
          - "*Cache*"
          - "*cache*"
          - "*History*"
          - "*Local Storage*"
          - "*Session Storage*"
          - "*SharedStorage*"
          - "*WebStorage*"
          - "*blob_storage*"
          - "*Favicons*"
      when: config_dir.stat.exists
      register: archive_result

    - name: Copy archive to local machine
      fetch:
        src: "{{ backup_remote_path }}"
        dest: "{{ backup_local_path }}"
        flat: yes
      when: archive_result.changed | default(false)

    - name: Delete archive from remote
      file:
        path: "{{ backup_remote_path }}"
        state: absent
      when: archive_result.changed | default(false)

    - name: Show success result
      debug:
        msg: "Succsessfully saved backup to {{ backup_local_path }}"
      when: archive_result.changed | default(false)

    - name: Show result when config directory does not exist
      debug:
        msg: "No configuration found at {{ backup_remote_path }}. No backup created."
      when: not config_dir.stat.exists
