---
- hosts: dev
  become: true

  vars:
    backup_remote_path: "/home/{{ desktop_user }}/chromium-backup.tar.gz"
    backup_local_path: "{{ playbook_dir }}/../configuration{{ backup_remote_path }}"

  tasks:

    - name: Check if Chromium config directory exists
      stat:
        path: "/home/{{ desktop_user }}/snap/chromium/common/chromium/Default"
      register: chromium_config_dir

    - name: Create tar.gz archive of Chromium settings
      archive:
        path: "/home/{{ desktop_user }}/snap/chromium/common/chromium/Default"
        dest: "{{ backup_remote_path }}"
        format: gz
        exclusion_patterns:
          - "*Cache*"
          - "*cache*"
          - "History*"
          - "Local Storage*"
          - "Session Storage*"
          - "SharedStorage*"
          - "WebStorage*"
          - "blob_storage*"
          - "Favicons*"
      when: chromium_config_dir.stat.exists
      register: archive_result

    - name: Fetch backup file to local machine
      fetch:
        src: "{{ backup_remote_path }}"
        dest: "{{ backup_local_path }}"
        flat: yes
      when: archive_result.changed | default(false)

    - name: Delete backup file from remote server
      file:
        path: "{{ backup_remote_path }}"
        state: absent
      when: archive_result.changed | default(false)

    - name: Show backup status
      debug:
        msg: "Chromium backup completed successfully. Backup saved to {{ backup_local_path }}"
      when: archive_result.changed | default(false)

    - name: Show backup status when no Chromium configuration exists
      debug:
        msg: "No Chromium configuration found at /home/{{ desktop_user }}/snap/chromium/common/chromium/Default. No backup created."
      when: not chromium_config_dir.stat.exists
