---
- import_playbook: setup-users.yml
- import_playbook: setup-basics.yml
- import_playbook: setup-nodejs.yml

# Apply linux roles
- import_playbook: configure-profile-roles.yml

# Finally, reboot the system if required
- import_playbook: reboot-if-required.yml
