---
- hosts: all
  become: true

  vars_files:
    - vars.yml

  vars_prompt:
    - name: ssh_public_key
      prompt: "Enter the SSH public key for all users"
      private: no

    - name: ansible_user_password
      prompt: "Enter the password for the ansible user {{ ansible_user_name }}"
      private: yes

    - name: desktop_user_password
      prompt: "Enter the password for the desktop user {{ desktop_user_name }}"
      private: yes

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

  tasks:
    - name: Setup user accounts
      no_log: true # Prevent logging the passwords
      user:
        name: "{{ item.user }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
      loop:
        - { user: "{{ ansible_user_name }}", password: "{{ ansible_user_password }}" }
        - { user: "{{ desktop_user_name }}", password: "{{ desktop_user_password }}" }

    - name: Allow passwordless sudo for ansible user
      lineinfile:
        path: /etc/sudoers.d/50-ansible-user-does-not-need-password
        regexp: '^{{ ansible_user_name }}'
        line: '{{ ansible_user_name }} ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
        create: yes
        state: present

    - name: Add SSH public key to all users
      authorized_key:
        user: "{{ item }}"
        key: "{{ ssh_public_key }}"
        state: present
      loop:
        - "root"
        - "{{ ansible_user_name }}"
        - "{{ desktop_user_name }}"

    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify: Restart SSH
    
    - name: Disable password authentication for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH
