---
- name: Configure basic profile linux roles
  hosts: linux
  become: true

  vars:
    ansible_user: "{{ my_ansible_user }}"
    desktop_user_names: "{{ desktop_users | map(attribute='name') | list }}"

  roles:
    - podman
    - tmux
    - ruby
    - python
    - dolt_sql_server
    - claude_code
