---
- hosts: all
  become: true

  vars:
    desktop_user_name: "galadriel"

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all packages
      apt: upgrade=safe

  handlers:
    - name: Restart XRDP
      service:
        name: xrdp
        state: restarted

  tasks:
    - name: Print the user name
      debug:
        msg: "The desktop user is {{ desktop_user_name }}"

    - name: Set timezone to Europe/Berlin
      timezone:
        name: Europe/Berlin

    - name: Install minimal GNOME desktop
      apt:
        name:
          - build-essential
          - dotnet-sdk-8.0
          - keepassxc
          - seahorse
          - ubuntu-desktop-minimal
        state: present

    - name: Remove GNOME remote desktop
      apt:
        name: gnome-remote-desktop
        state: absent
    
    - name: Install XFCE desktop and XRDP
      apt:
        name:
          - xfce4
          - xfce4-goodies
          - xrdp
        state: present

    - name: Start and enable XRDP
      service:
        name: xrdp
        state: started
        enabled: yes

    - name: Remove light-locker
      apt:
        name: light-locker
        state: absent

    # The user account may not be modified if it already exists, because
    # that would change the password.
    - name: Check whether user {{ desktop_user_name }} exists
      getent:
        database: passwd
        key: "{{ desktop_user_name }}"
      register: user_result
      ignore_errors: yes
      changed_when: false

    - name: Create account {{ desktop_user_name }} if it does not exist
      user:
        name: "{{ desktop_user_name }}"
        password: "{{ desktop_user_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
      when: user_result.failed

    - name: Check whether the file .xsession exists for {{ desktop_user_name }}
      stat:
        path: "/home/{{ desktop_user_name }}/.xsession"
      register: xsession_file
      ignore_errors: yes
      changed_when: false

    - name: Create .xsession for {{ desktop_user_name }} if it does not exist
      file:
        path: /home/galadriel/.xsession
        state: touch
        owner: galadriel
        group: galadriel
        mode: 0644
      when: not xsession_file.stat.exists

    - name: Enable XFCE session for {{ desktop_user_name }}
      lineinfile:
        dest: "/home/{{ desktop_user_name }}/.xsession"
        regexp: '^.*'
        line: xfce4-session
        state: present
      notify: Restart XRDP

  post_tasks:
    - name: Clean up apt cache and unused packages
      apt:
        autoremove: yes
        autoclean: yes
