---
- name: Restore home folder files
  hosts: linux
  become: true

  vars_files:
    - vars-usernames.yml
    - vars-secrets.yml

  vars:
    ansible_user: "{{ my_ansible_user }}"
    desktop_user_names: "{{ desktop_users | map(attribute='name') | list }}"
    backup_remote_path: "/tmp/home-folder-files-backup.tar.gz"
    backup_local_path: "{{ playbook_dir }}/../configuration/home/my_desktop_user/home-folder-files-backup.tar.gz"

  tasks:

    # TODO: smell - complicated error handling - consider using `block`, `rescue`, `always` - see p. 121 (147 in PDF) of Ansible for DevOps
    - name: Check if backup file exists locally
      delegate_to: localhost
      become: false
      stat:
        path: "{{ backup_local_path }}"
      register: backup_local

    - name: Upload home folder files backup to remote server
      copy:
        src: "{{ backup_local_path }}"
        dest: "{{ backup_remote_path }}"
      when: backup_local.stat.exists
      register: upload_result

    - name: Extract home folder files backup
      become_user: "{{ item }}"
      unarchive:
        src: "{{ backup_remote_path }}"
        dest: "/home/{{ item }}/"
        owner: "{{ item }}"
        group: "{{ item }}"
        remote_src: yes
      loop: "{{ desktop_user_names }}"
      when: not upload_result.failed | default(true)

    - name: Remove temporary archive
      file:
        path: "{{ backup_remote_path }}"
        state: absent
      ignore_errors: true
