---
- hosts: linux
  tags: not-supported-on-vagrant-docker
  become: true

  # TODO: smell - copied from restore-chromium-settings.yml - can we abstract this?
  vars_files:
    - vars-usernames.yml
    - vars-secrets.yml

  vars:
    ansible_user: "{{ my_ansible_user }}"
    desktop_user_names: "{{ desktop_users | map(attribute='name') | list }}"
    backup_remote_path: "/tmp/vscode-backup.tar.gz"
    backup_local_path: "{{ playbook_dir }}/../configuration/home/my_desktop_user/vscode-backup.tar.gz"

  tasks:

    # TODO: smell - complicated error handling - consider using `block`, `rescue`, `always` - see p. 121 (147 in PDF) of Ansible for DevOps

    - name: Check if archive exists locally
      delegate_to: localhost
      become: false
      stat:
        path: "{{ backup_local_path }}"
      register: backup_local

    - name: Upload archive to remote server
      copy:
        src: "{{ backup_local_path }}"
        dest: "{{ backup_remote_path }}"
      when: backup_local.stat.exists
      register: upload_result

    - name: Remove existing config directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/home/{{ item }}/.vscode"
        - "/home/{{ item }}/.config/Code/User"
      loop: "{{ desktop_user_names }}"
      when: not upload_result.failed | default(true)

    - name: Extract archive
      become_user: "{{ item }}"
      unarchive:
        src: "{{ backup_remote_path }}"
        dest: "/home/{{ item }}/"
        owner: "{{ item }}"
        group: "{{ item }}"
        remote_src: yes
      loop: "{{ desktop_user_names }}"
      when: not upload_result.failed | default(true)

    - name: Remove temporary archive
      file:
        path: "{{ backup_remote_path }}"
        state: absent
      ignore_errors: true

    - name: Install VSCode extensions
      shell: cat /home/{{ item }}/vscode-extension-list.txt | xargs -n 1 code --force --install-extension
      become_user: "{{ item }}"
      loop: "{{ desktop_user_names }}"
      when: not upload_result.failed | default(true)

    - name: Remove extensions list
      file:
        path: "/home/{{ item }}/vscode-extension-list.txt"
        state: absent
      loop: "{{ desktop_user_names }}"
      ignore_errors: true
