---
- name: Restore keyring
  hosts: linux
  tags: not-supported-on-vagrant-docker
  become: true

  vars:
    ansible_user: "{{ my_ansible_user }}"

  tasks:
    - name: Restore keyring
      include_tasks: tasks/restore.yml
      vars:
        users: "{{ desktop_users | map(attribute='name') | list }}"
        source_path: "{{ playbook_dir }}/../configuration/home/my_desktop_user/keyrings-backup.tar.gz"
        destination_beneath_home: ".local/share/keyrings"
        delete_before_beneath_home:
          - ".local/share/keyrings"
