---
- name: Restore home folder files
  hosts: linux
  become: true

  vars_files:
    - vars-usernames.yml
    - vars-secrets.yml

  vars:
    ansible_user: "{{ my_ansible_user }}"

  tasks:

    - name: Restore home folder files
      include_tasks: tasks/restore.yml
      vars:
        users: "{{ desktop_users | map(attribute='name') | list }}"
        source_path: "{{ playbook_dir }}/../configuration/home/my_desktop_user/home-folder-files-backup.tar.gz"
        destination_beneath_home: ""
