---
- name: Restore Chromium settings
  hosts: linux
  tags: not-supported-on-vagrant-docker
  become: true

  vars_files:
    - vars-usernames.yml
    - vars-secrets.yml

  vars:
    ansible_user: "{{ my_ansible_user }}"

  tasks:

    - name: Restore Chromium settings
      include_tasks: tasks/restore.yml
      vars:
        users: "{{ desktop_users | map(attribute='name') | list }}"
        source_path: "{{ playbook_dir }}/../configuration/home/my_desktop_user/chromium-backup.tar.gz"
        destination_beneath_home: "snap/chromium/common/chromium/Default"
        delete_before_beneath_home:
          - "snap/chromium/common/chromium/Default"
