---
- hosts: dev
  become: true

  handlers:
    # TODO: smell - cleanup apt cache is duplicate in several playbooks
    - name: Cleanup apt cache
      apt:
        autoremove: yes
        autoclean: yes

  tasks:

    #####
    # Install and configure Chromium
    #####

    # Visual Studio Code requires Chromium for key management. Thus, Chromium is
    # installed first.
    # See: https://code.visualstudio.com/docs/configure/settings-sync#_troubleshooting-keychain-issues
    - name: Install Chromium
      snap: name=chromium state=present

    # Recursively copy configuration/etc/chromium-browser/policies
    #
    # Policy configuration is described in
    #
    # - https://www.chromium.org/administrators/linux-quick-start/
    # - https://chromeenterprise.google/policies/
    #
    # More information on Chromium policies
    #
    # https://www.chromium.org/administrators/policy-templates/
    #
    # How to set up a default configuration - for the first start only -
    # and policies
    #
    # https://www.chromium.org/administrators/configuring-other-preferences/
    #
    - name: Update Chromium policies
      synchronize:
        src: "../configuration/etc/chromium-browser/"
        dest: "/etc/chromium-browser"
        delete: true
        recursive: true

    - name: Set ownership of Chromium policies
      file:
        path: "/etc/chromium-browser"
        recurse: true
        owner: root
        group: root
        mode: "0755"

    # Upload and extract chromium backup
    - name: Check if backup file exists locally
      delegate_to: localhost
      become: false
      stat:
        path: "{{ playbook_dir }}/../configuration/home/{{ desktop_user }}/chromium-backup-*.tar.gz"
      register: backup_file_stat

    - name: Find most recent backup file
      delegate_to: localhost
      become: false
      shell: "ls -t {{ playbook_dir }}/../configuration/home/{{ desktop_user }}/chromium-backup-*.tar.gz | head -1"
      register: latest_backup
      changed_when: false
      when: backup_file_stat.stat.exists | default(false)

    - name: Check if Chromium profile directory exists
      stat:
        path: "/home/{{ desktop_user }}/snap/chromium/common/chromium/Default"
        follow: yes
      register: chromium_profile_dir
      when: backup_file_stat.stat.exists | default(false)
      
    - name: Remove existing Chromium profile if it exists
      file:
        path: "/home/{{ desktop_user }}/snap/chromium/common/chromium/Default"
        state: absent
      when: backup_file_stat.stat.exists | default(false) and chromium_profile_dir.stat.exists | default(false)

    - name: Ensure Chromium base directory exists
      file:
        path: "/home/{{ desktop_user }}/snap/chromium/common/chromium"
        state: directory
        mode: '0755'
        owner: "{{ desktop_user }}"
        group: "{{ desktop_user }}"
      when: backup_file_stat.stat.exists | default(false)

    - name: Upload Chromium backup file to remote server
      copy:
        src: "{{ latest_backup.stdout }}"
        dest: "/home/{{ desktop_user }}/chromium-backup.tar.gz"
        owner: "{{ desktop_user }}"
        group: "{{ desktop_user }}"
        mode: '0644'
      when: backup_file_stat.stat.exists | default(false)
      register: upload_result

    - name: Extract Chromium backup
      become_user: "{{ desktop_user }}"
      unarchive:
        src: "/home/{{ desktop_user }}/chromium-backup.tar.gz"
        dest: "/home/{{ desktop_user }}/snap/chromium/common/chromium/"
        remote_src: yes
      when: upload_result.changed | default(false)
      register: extract_result

    - name: Remove temporary archive from remote server
      file:
        path: "/home/{{ desktop_user }}/chromium-backup.tar.gz"
        state: absent
      when: extract_result.changed | default(false)

    - name: Show restore status
      debug:
        msg: "Chromium profile restored successfully from {{ latest_backup.stdout | basename }}"
      when: extract_result.changed | default(false)

    - name: Show status when no backup found
      debug:
        msg: "No Chromium backup found. Skipping restore."
      when: not backup_file_stat.stat.exists | default(false)

    #####
    # Install and configure Visual Studio Code
    #####
    # Adopted from https://code.visualstudio.com/docs/setup/linux

    # Check if the Microsoft signing key is already installed
    - name: Check if Microsoft apt key is already installed
      command: >
        gpg --list-keys --keyring /etc/apt/keyrings/packages.microsoft.gpg
      register: have_microsoft_key
      changed_when: false
      failed_when: false

    # Warning:
    #   To install the Microsoft signing key,
    #   do not use apt_key module, because it is deprecated.
    #
    # Instead follow the instructions at
    # https://code.visualstudio.com/docs/setup/linux
    - name: Download Microsoft apt key to /tmp
      get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /tmp/microsoft.asc
      when: have_microsoft_key.rc != 0

    - name: Dearmor Microsoft apt key
      command: gpg --dearmor /tmp/microsoft.asc
      args:
        creates: /tmp/microsoft.asc.gpg
      when: have_microsoft_key.rc != 0

    - name: Install Microsoft apt key to /etc/apt/keyrings
      # Instead of using the copy module, use the install command
      command: >
        install -D -o root -g root -m 644
                /tmp/microsoft.asc.gpg
                /etc/apt/keyrings/packages.microsoft.gpg
      when: have_microsoft_key.rc != 0

    - name: Remove Microsoft apt key from /tmp
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/microsoft.asc
        - /tmp/microsoft.asc.gpg
      when: have_microsoft_key.rc != 0

    # Include arm64 architecture to support Apple Silicon when running
    # on the Vagrant / Tart test environment
    - name: Add Microsoft apt repository
      apt_repository:
        repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
        state: present

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Update apt cache
      apt: update_cache=yes

    - name: Install VS Code
      apt:
        name: code
        state: present
      notify: Cleanup apt cache

    # Configure keyring as described in
    # https://code.visualstudio.com/docs/configure/settings-sync#_troubleshooting-keychain-issues
    - name: Configure keyring
      become_user: "{{ desktop_user }}"
      lineinfile:
        path: /home/{{ desktop_user }}/.vscode/argv.json
        insertafter: '^{$'
        line: '	"password-store": "gnome-libsecret",'
        state: present
