---
# After reading the following websites I decided to use snap to install Chrome
#
# - https://www.xda-developers.com/how-install-chrome-ubuntu/
# - https://wiki.ubuntuusers.de/Google_Chrome/
#
- hosts: dev
  become: true

  tasks:

    - name: Install Chrome
      snap: name=chromium state=present
