---
- hosts: all
  become: true

  pre_tasks:
    # TODO: smell - Update apt cache is duplicate in several playbooks
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    # TODO: smell - cleanup apt cache is duplicate in several playbooks
    - name: Cleanup apt cache
      apt:
        autoremove: yes
        autoclean: yes

    - name: Restart XRDP
      service:
        name: xrdp
        state: restarted

  tasks:
    - name: Install console utilities
      apt:
        name:
          - tree
        state: present
      notify: Cleanup apt cache

    - name: Install minimal GNOME desktop
      apt:
        name:
          - build-essential
          - dotnet-sdk-8.0
          - keepassxc
          - dbus-x11
          - libsecret-tools
          - seahorse
          - ubuntu-desktop-minimal
        state: present
      notify: Cleanup apt cache

    - name: Remove GNOME remote desktop
      apt:
        name: gnome-remote-desktop
        state: absent
      notify: Cleanup apt cache
    
    - name: Install XFCE desktop and XRDP
      apt:
        name:
          - xfce4
          - xfce4-goodies
          - xrdp
        state: present
      notify: Cleanup apt cache

    - name: Start and enable XRDP
      service:
        name: xrdp
        state: started
        enabled: yes

    - name: Remove light-locker
      apt:
        name: light-locker
        state: absent
      notify: Cleanup apt cache

    - name: Enable XFCE session for {{ desktop_user }}
      lineinfile:
        dest: "/home/{{ desktop_user }}/.xsession"
        regexp: '^.*'
        line: xfce4-session
        create: yes
        owner: galadriel
        group: galadriel
        mode: 0644
        state: present
      notify: Restart XRDP

