---
- hosts: linux
  become: true
  
  vars:
    ansible_user: "{{ my_ansible_user }}"

  tasks:
    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install global NPM packages
      npm:
        name: "{{ item }}"
        global: true
      loop:
        - typescript
        - "@anthropic-ai/claude-code"
