---
# Create default GNOME keyring for the desktop user
#
# Adopted from
# https://unix.stackexchange.com/questions/473528/how-do-you-enable-the-secret-tool-command-backed-by-gnome-keyring-libsecret-an
#
- hosts: dev
  tags: not-supported-on-vagrant-docker
  become: true

  vars_files:
    - vars-usernames.yml
    - vars-secrets.yml

  vars:
    ansible_user: "{{ my_ansible_user }}"
    desktop_user_names: "{{ desktop_users | map(attribute='name') | list }}"

  pre_tasks:
    # TODO: smell - Update apt cache is duplicate in several playbooks
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    # TODO: smell - cleanup apt cache is duplicate in several playbooks
    - name: Cleanup apt cache
      apt:
        autoremove: yes
        autoclean: yes

  tasks:
    - name: Install keyring dependencies
      apt:
        name:
          - dbus-x11
          - libsecret-tools
        state: present
      notify: Cleanup apt cache

    - name: Upload create-default-gnome-keyring.sh script
      copy:
        src: ./scripts/create-default-gnome-keyring.sh
        dest: /tmp/create-default-gnome-keyring.sh
        mode: '0755'

    - name: Create GNOME keyring for {{ desktop_user_names | join(', ') }}
      shell: |
        /tmp/create-default-gnome-keyring.sh "{{ gnome_keyring_password }}"
      become_user: "{{ item }}"
      loop: "{{ desktop_user_names }}"

    - name: Remove temporary script
      file:
        path: /tmp/create-default-gnome-keyring.sh
        state: absent