---
- hosts: all
  become: true

  handlers:
    - name: Cleanup apt cache
      apt:
        autoremove: yes
        autoclean: yes

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all packages
      apt: upgrade=safe
      notify: Cleanup apt cache

    - name: Check if reboot is required
      stat: path=/var/run/reboot-required get_checksum=no
      register: reboot_required
      changed_when: false

    - name: Reboot if required
      reboot:
      when: reboot_required.stat.exists == true

  tasks:
    - name: Set timezone to Europe/Berlin
      timezone:
        name: Europe/Berlin
