---
- hosts: all
  remote_user: root
  become: true
  
  vars_files:
    - vars-usernames.yml
    - vars-secrets.yml

  vars:
    ansible_user: "{{ admin_user_on_fresh_system }}"

    users:
      - name: "{{ my_ansible_user }}"
        password: "{{ my_ansible_user_password | default('{{ secrets must be specified in vars-secrets.yml }}') }}"
      - name: "{{ my_desktop_user }}"
        password: "{{ my_desktop_user_password | default('{{ secrets must be specified in vars-secrets.yml }}') }}"

    ssh_public_key: "{{ my_ssh_public_key | default('secrets must be specified in vars-secrets.yml') }}"

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

  tasks:
    - name: Setup user accounts
      no_log: true # Prevent logging the passwords
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
      loop: "{{ users }}"

    - name: Allow passwordless sudo for ansible user
      lineinfile:
        path: /etc/sudoers.d/50-ansible-user-does-not-need-password
        regexp: '^{{ my_ansible_user }}'
        line: '{{ my_ansible_user }} ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
        create: yes
        state: present

    - name: Add SSH public key to all users
      no_log: true # Prevent logging the passwords
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ ssh_public_key }}"
        state: present
      loop: "{{ users }}"
    
    - name: Disable password authentication for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH