tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: "↑"
    behind: "↓"
    staged: "+"
    conflict: "!"
    modified: "*"
    untracked: "?"
    stashed: "$"
    clean: ""
  styles:
    clear: "#[default]"
    state: "#[fg=red,bold]"
    branch: "#[fg=white,bold]"
    remote: "#[fg=cyan]"
    staged: "#[fg=green]"
    conflict: "#[fg=red,bold]"
    modified: "#[fg=yellow]"
    untracked: "#[fg=grey]"
    stashed: "#[fg=cyan]"
    clean: "#[fg=green]"
  layout:
    - branch
    - " "
    - flags
