---
# AWS Linux-specific overrides
# These override both platform and provider defaults

# Ubuntu 24.04 LTS in eu-north-1
#
# Use the EC2 AMI locator for Ubuntu to find the latest AMI:
# https://cloud-images.ubuntu.com/locator/ec2/
#
# Just enter the distribution (e.g., "noble") and the region (e.g.,
# "eu-north-1") into the search box.
#
aws_default_ami_id: "ami-081c358c86e68b9f9"

# The following table gives an overview of server types and prices for servers
# Last updated: 2025-07-13
#
# | Server Type | Price per hour | vCPUs | RAM   |
# |-------------|----------------|-------|-------|
# | t3.micro    | $ 0.0104       | 2     | 4 GB  |
# | t3.medium   | $ 0.0418       | 2     | 4 GB  |
# | t3.large    | $ 0.0835       | 2     | 8 GB  |
# | t3.xlarge   | $ 0.1670       | 4     | 16 GB |
#
# Lookup current values at https://aws.amazon.com/ec2/instance-types/t3/
# or check `aws ec2 describe-instance-types`.
#
# NOTE: t3.micro is sufficient for testing and it is free tier eligible.
#
aws_default_instance_type: "t3.micro"

admin_user_on_fresh_system: "ubuntu"
